# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
