# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200327_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_alert',
            field=models.IntegerField(default=0),
        ),
    ]
